server:
  port: 8081

spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            maxAge: 3600
      routes:
        - id: usuario-service
          uri: http://usuario:8084
          predicates:
            - Path=/api/usuarios/**
          filters:
            - StripPrefix=1
        - id: sala-service
          uri: http://sala:8082
          predicates:
            - Path=/api/salas/**
          filters:
            - StripPrefix=1
        - id: reserva-service
          uri: http://reserva:8083
          predicates:
            - Path=/api/reservas/**
          filters:
            - StripPrefix=1

# Configuração do Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always